defaultAssertionDataset: superform_assertion_249504861
defaultDataset: superform_outputs_249504861
defaultLocation: europe-west1
defaultProject: gtm-k3vhstz-ztmwy
vars:
  GA4_DATASET: analytics_249504861
  LOCAL_TIMEZONE: Europe/Brussels
  OUTPUTS_DATASET: superform_outputs_249504861
  QUALITY_DATASET: superform_quality_249504861
  TRANSFORMATIONS_DATASET: superform_transformations_249504861
